import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { ClerkProvider } from "@clerk/nextjs"
import { YearProvider } from "@/components/context/YearContext"
import { ModalProvider } from "@/components/providers/modal-provider"
import Header from "@/components/sections/header/header"
import { getAllYearsWithPages, getLatestYearWithPages } from "./action"
import { ThemeProvider } from "@/components/providers/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "CAC",
  description: "Generated by Supernova",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const years = await getAllYearsWithPages();
  const initialYear = years[0] || null;

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased custom-scrollbar`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <YearProvider initialYear={initialYear}>
              <Header years={years} />
              {children}
              <ModalProvider />
            </YearProvider>
            <Toaster position="bottom-center" />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}

